### ISSUE TITLE
Add background image to the scene

### ISSUE THREAD

**Issue by pragmatically-dev** [omchiii/model_viewer_plus.dart#12]
Is there any way to add a background image and replace the white background?

**Comment by Foldblade** [comment]
Do you mean something like [https://modelviewer.dev/examples/lightingandenv/](https://modelviewer.dev/examples/lightingandenv/) or [https://modelviewer.dev/examples/lightingandenv/#environmentLighting](https://modelviewer.dev/examples/lightingandenv/#environmentLighting), or you just hope to add a 2D image as its background?

This package does not implement all the functions of model-viewer, though I'm willing to have a try, but it may still take a long time. 

If you need functions like [lighting and env](https://modelviewer.dev/examples/lightingandenv/) of model-viewer, I'd be happy to try to implement one or two of them. Otherwise, if you just want to add a image as its lower layer, the solution I have in mind is: 

```
Stack(
  children: [
    Image.network(
        'https://storage.googleapis.com/cms-storage-bucket/50c707a80fe015e19d39.png'),
    ModelViewer(
      backgroundColor: Color.fromARGB(0x00, 0xEE, 0xAA, 0xAA), // Set background color to transparent
      src: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
      alt: "A 3D model of an astronaut",
      ar: true,
      autoRotate: true,
      cameraControls: true,
    )
  ],
)
```

The result:

![qemu-system-x86_64_H3wkxbHMJA](https://user-images.githubusercontent.com/25426917/158055836-9c7861db-a441-4f7d-8a94-ea7371da01ec.png)

This works on Web now, but on Android / iOS, we need to make the Webview's background transparent. 

Can the solution I proposed meet your needs? Please let me know, and I'll commit the modification later.

**Comment by pragmatically-dev** [comment]
Thank you so much sir I'm grateful, your solution has helped me
