### ISSUE TITLE
Image/poster display while 3D model Loads

### ISSUE THREAD

**Issue by muazbutt9** [omchiii/model_viewer_plus.dart#26]
I want to show the image of the 3D model from the server until the complete model loads.  I am using the constructor like this, but the poster is not loading or showing anything. 

> `ModelViewer(
                              src: widget.sourceUrl,
                              poster: "https://ecommerce.munib.ml/storage/2022/03/chair-Beech.png",
                              alt: "A 3D model of an astronaut",
                              ar: true,
                              autoRotate: true,
                              cameraControls: true,

**Comment by Foldblade** [comment]
Tested on Web and Android, it works. 

Maybe it is just too fast to load the model, so the poster will not display? 🤔

![web](https://user-images.githubusercontent.com/25426917/168742492-5cc60b51-9bf4-4f5b-a6e3-de30f0b632ef.gif)

![android](https://user-images.githubusercontent.com/25426917/168742479-db282a10-3891-45ac-b717-60b25711e994.gif)

**Comment by muazbutt9** [comment]
@Foldblade 

Have a look below, the 3D model from the server is loading but no image is displayed, i am using a direct link, for now, once that'll work i will say the dynamic one from the server. 


![442ba0d6-c352-4da2-87d6-8ca4a7cbac3d](https://user-images.githubusercontent.com/29090435/168747812-50bbdcba-e375-4d0b-b441-b040f39c4261.jpg)

**Comment by muazbutt9** [comment]
BTW My constructor look like this 

`class ModelViewer extends StatefulWidget {
  ModelViewer(
      {Key? key,
      this.backgroundColor = Colors.transparent,
      required this.src,
      this.alt,
      this.poster,
      this.ar,
      this.arModes,
      this.arScale,
      this.autoRotate,
      this.autoRotateDelay,
      this.autoPlay,
      this.cameraControls,
      this.iosSrc,})
      : super(key: key);
`

**Comment by muazbutt9** [comment]
@Foldblade please let me know. Thanks in advance

**Comment by Foldblade** [comment]
<small>*English is not my native language; sorry for possible mistake in getting your points.*</small>

Since there is no image displayed, I think there may be something wrong with the poster's URL. For example, if the request for the poster image's URL returns 404, this problem will not display in the console.

I'm not very sure what your "direct link" means. What I can say is, in version 1.2.0, the `poster` parameter only supports absolute URLs like "https://example.com/examplePoster.png", so `poster: "https://ecommerce.munib.ml/storage/2022/03/chair-Beechs.png"` should work. Relative paths like "assets/examplePoster.png" are not currently supported.

Sorry, but without further code, I can only suggest you make some `debugPrint` to check the poster's URL, or try to test in the Flutter Web, and to see if there is anything wrong with the request of the poster image in the browser's developer's mode.

---

BTW, I'm also curious about your posted constructor:

> `class ModelViewer extends StatefulWidget { ModelViewer( {Key? key, this.backgroundColor = Colors.transparent, required this.src, this.alt, this.poster, this.ar, this.arModes, this.arScale, this.autoRotate, this.autoRotateDelay, this.autoPlay, this.cameraControls, this.iosSrc,}) : super(key: key); `

This looks quite different with code starting from https://github.com/omchiii/model_viewer_plus.dart/blob/6ecc434cbe5f314bd903ec8ec6b45263bdbbf94c/lib/src/model_viewer_plus.dart#L19

Does this mean you encapsulate this package's `ModelViewer` class with your own `ModelViewer` class? Or did you modify the source code? Or just it looks too long, so you abridged it?

---

<details>
<summary>Here attached is my successful test:</summary>

```dart
import 'package:flutter/material.dart';
import 'package:model_viewer_plus/model_viewer_plus.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text("Model Viewer")),
        body: ModelViewer(
          backgroundColor: Color.fromARGB(0xFF, 0xEE, 0xEE, 0xEE),
          src: 'assets/Astronaut.glb', // a bundled asset file
          alt: "A 3D model of an astronaut",
          ar: true,
          poster: "https://ecommerce.munib.ml/storage/2022/03/chair-Beechs.png",
          arModes: ['scene-viewer', 'webxr', 'quick-look'],
          autoRotate: true,
          cameraControls: true,
          iosSrc: 'https://modelviewer.dev/shared-assets/models/Astronaut.usdz',
        ),
      ),
    );
  }
}
```
</details>

**Comment by muazbutt9** [comment]
Hey, @Foldblade the issue is solved but receiving an intent error while opening in AR, the 3D model does not loads.

Here is my 3D Model: https://ecommerce.munib.ml/storage/2022/03/chair-Beech.glb
