### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by zakarya0** [omchiii/model_viewer_plus.dart#57]
Hello, I faced this issue, I have a .glb file stored in Laravel project on server, but when I want to use the file inside my flutter app it says **("Access to fetch at 'http://10.0.2.2:8000/3d/1.glb' (redirected from 'http://127.0.0.1:45685/model') from origin 'http://127.0.0.1:45685' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.")**
Does anyone know how to configure Laravel backend to be able to load the file?

Thanks.

**Comment by Foldblade** [comment]
I think this issue is not related with model-viewer-plus. Because your server side(10.0.2.2) didn't have the  'Access-Control-Allow-Origin' header, when you run Flutter project on 127.0.0.1, the cross-origin issue occured.
You should try to add 'Access-Control-Allow-Origin' header to your Laravel's response. Maybe try https://github.com/fruitcake/laravel-cors ?
