### ISSUE TITLE
Trying to click on the AR preview button in iOS results in error

### ISSUE THREAD

**Issue by stijnie2210** [omchiii/model_viewer_plus.dart#8]
Describe the bug
on iOS (with a usdz file) the model loads, but when i click on the AR button the following error occurs in the terminal:
```
flutter: >>>> ModelViewer failed to load: Error Domain=WebKitErrorDomain Code=102 "Frame load interrupted" UserInfo={_WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x6000031747c0>, NSErrorFailingURLStringKey=https://raw.githubusercontent.com/kcoley/usdz_test_models/dev/Output/BoomBox/BoomBox.usdz, NSErrorFailingURLKey=https://raw.githubusercontent.com/kcoley/usdz_test_models/dev/Output/BoomBox/BoomBox.usdz, NSLocalizedDescription=Frame load interrupted} (null 102)
```

To reproduce
on iOS 15.3, load any usdz file into the `ModelViewer` widget and click on the AR button. Could be checked out via the example project.

Smartphone (please complete the following information):

Device: iPhone 12 pro max
OS: iOS 15.3.1
Version: 1.1.2

**Comment by omchiii** [comment]
Could you please record? ARView should be only available for android devices, even the button should not appear.

**Comment by stijnie2210** [comment]
@omchiii That doesn't seem entirely logical. In the documentation it says `iosSrc` is meant to be able to contain a path to a `usdz` file while should be opened in AR QuickLook. If it's not supposed to do that I don't see why it would contain the `iosSrc` path. You're correct that it doesn't show the button if you don't add anything to the iosSrc, but as soon as you do the button appears.

https://user-images.githubusercontent.com/8982310/155956455-5218be16-8938-47ca-8fed-f2905836dd8a.MP4


Anyway, I've attached my screenrecording:
You can see the model is displayed fine, but tapping on the button does nothing except that the button border becomes blue and it prints an error in the terminal.

**Comment by omchiii** [comment]
Thank you. You are right. Will have a look into it.

**Comment by Foldblade** [comment]
This package use WebView for the display of model-viewer on Android & iOS. On iOS Platform, after you click on the AR preview button, model-viewer will redirect the browser to the usdz file's url. According to https://github.com/react-native-webview/react-native-webview/issues/1242#issuecomment-673910314 , to open usdz model in AR Quick Look, iOS WebView should be **SFSafariViewController** instead of **WKWebView**.

This package uses [webview_flutter](https://pub.dev/packages/webview_flutter) which is backed by a [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview), so I think that's the problem. 

I have no experience on iOS development. A less elegant solution I made in https://github.com/omchiii/model_viewer_plus.dart/pull/16/commits/7974cd626969623d174f942620c141d7fea47951 is: using [url_launcher](https://pub.dev/packages/url_launcher) to open the usdz file in SFSafariViewController, and then you can open it in AR Quick Look.

![Simulator Screen Shot - iPhone 13 Pro - 2022-03-15 at 16 43 32](https://user-images.githubusercontent.com/25426917/158345641-27beaa5d-d0d2-46d8-bd51-86229c85080f.png)

Hoping there can be a more elegant solution.

**Comment by omchiii** [comment]
https://github.com/omchiii/model_viewer_plus.dart/issues/50#issuecomment-1445153679
